GET http://localhost:3000/wallets/

###

GET http://localhost:3000/wallets/4

###

DELETE http://localhost:3000/wallets/8

###

POST http://localhost:3000/wallets/
Content-Type: application/json

{
  "owner": "R",
  "coin": "BTC",
  "quantity": 0.11,
  "color": "#FFAAAA"
}

###

PATCH http://localhost:3000/wallets/4
Content-Type: application/json 

{
  "owner": "A",
  "coin": "MCO",
  "quantity": 0.11,
  "color": "#FFFFFF"
}